### ISSUE TITLE
add option to save Pins at specified place

### ISSUE THREAD

**Issue by GitMensch** [SaekiRaku/vscode-pin-up#17]
I often work on a read-only workspace an when using Pin Up there receive error messages:

```
exthost] [error] Error: EPERM: operation not permitted, mkdir 'x:\SOME\src\.vscode'
	at mkdirSync (fs.js:823:3)
	at Object.fs.mkdirSync (electron/js2c/asar.js:718:16)
	at PinDataProvider.refresh (c:\Users\USER\.vscode-oss\extensions\saekiraku.pin-up-1.4.0\src\PinDataProvider.js:142:20)
	at PinDataProvider.AddPin (c:\Users\USER\.vscode-oss\extensions\saekiraku.pin-up-1.4.0\src\PinDataProvider.js:168:18)
	at c:\Users\USER\.vscode-oss\extensions\saekiraku.pin-up-1.4.0\src\commands.js:13:23
```

Providing a setting where to store pins (for example `C:\User\${env:USER}\my-pins\${workspacename}`) would be a very useful thing.

**Comment by ItsCubeTime** [comment]
Maybe not ideal, but I guess https://github.com/SaekiRaku/vscode-pin-up/issues/24 could help with this.
